config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :renting_options do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end
  end
end

app/models/spree/line_item_decorator.rb
module Spree
  LineItem.class_eval do
    has_one :renting_option, through: :variant
    before_create :set_renting_end_date, if: Proc.new{ |l| l.renting_option.present? }

    scope :rentable, ->(){ where.not(renting_end_date: nil) }

    private
    def set_renting_end_date
      self.renting_end_date = eval("#{renting_option.period_quantity}.#{renting_option.normatized_period_type}").from_now.to_date
    end
  end
end

app/models/spree/option_type_decorator.rb
module Spree
  OptionType.class_eval do
    scope :without_renting_values,     ->(){ includes(:option_values).where(spree_option_values: { is_renting: false }) }
  end
end

app/models/spree/option_value_decorator.rb
module Spree
  OptionValue.class_eval do
    scope :not_renting,     ->(){ where(is_renting: false) }
  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
    [:renting_option, :renting_option_id,
      :spree_renting_option_id].each do |attr|
      delegate :"#{attr}", :"#{attr}=", to: :find_or_build_master
    end

    attr_accessor :renting_options

    has_many :option_types,             ->(){ without_renting_values },
                                        through: :product_option_types

    accepts_nested_attributes_for :master, allow_destroy: true, reject_if: :all_blank

    alias_method :old_variants_and_option_values_for, :variants_and_option_values_for
    def variants_and_option_values_for(pricing_options = Spree::Config.default_pricing_options)
      inner_variants = old_variants_and_option_values_for(pricing_options)
      inner_variants.sort_by{|v| v.sku.include?('buy') || v.option_values.map(&:name).include?('buy') ? 0 : 1 }
    end
  end
end

app/models/spree/renting_option.rb
module Spree
  class RentingOption < Spree::Base
    acts_as_list
    after_save :touch_all_variants

    has_many :variants, class_name: Spree::Variant,
                        foreign_key: 'spree_renting_option_id',
                        inverse_of: :renting_option,
                        dependent: :nullify

    validates :name, presence: true, uniqueness: { allow_blank: true }
    validates :period_quantity, :period_type, presence: true
    validates :period_quantity, numericality: { only_integer: true,
     greater_than_or_equal_to: 1 }

    enum period_type: { month: 0, day: 1, week: 2, year: 3 }

    default_scope { order(position: :asc) }

    def presentation
      "#{period_quantity} #{normatized_period_type}"
    end

    def normatized_period_type
      period_quantity > 1 || period_quantity == 0 ? period_type.pluralize : period_type.singularize
    end

    private
    def touch_all_variants
      variants.update_all(updated_at: Time.current)
    end
  end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    belongs_to :renting_option,        class_name: Spree::RentingOption,
                                       foreign_key: 'spree_renting_option_id'

    alias_attribute :renting_option_id, :spree_renting_option_id
    alias_attribute :renting_option_id=, :spree_renting_option_id=

    def options_text
      values = option_values.includes(:option_type)
      values_arr = values.sort_by do |option_value|
        option_value.option_type.position
      end.to_a.reject{|v| v.is_renting? }.map do |ov|
        "#{ov.option_type.presentation}: #{ov.presentation}"
      end

      list_str = values_arr.to_sentence({ words_connector: ", ", two_words_connector: ", " })
      purchasing_type_value = values.select{|v| v.is_renting? }.first
      list_str += ". " unless list_str.empty?
      list_str += (purchasing_type_value && purchasing_type_value.name == 'rent' ? "Rent" : "Buy now")
      list_str
    end
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
module Spree
  module Admin
    ProductsController.class_eval do
      create.before :attach_renting_definitions
      update.before :attach_renting_definitions
      create.after :create_renting_variants_if_needed

      private
      def attach_renting_definitions
        renting_ot_ids = Spree::OptionType.includes(:option_values)
          .where(spree_option_values: { is_renting: true }).pluck(:id)
        @object.option_type_ids |= renting_ot_ids
      end

      def create_renting_variants_if_needed
        if has_any_renting_options_params?
          master_attributes = @object.master.attributes.except('id', 'created_at', 'deleted_at', 'is_master')
          buy_ov = Spree::OptionValue.find_by(name: 'buy', is_renting: true)
          rent_ov = Spree::OptionValue.find_by(name: 'rent', is_renting: true)
          permitted_resource_params[:renting_options].reject(&:blank?).each_with_index do |ro, index|
            renting_option = Spree::RentingOption.find(ro)
            renting_variant = build_common_variant(master_attributes, rent_ov)
            renting_variant.sku = renting_variant.sku + "-#{renting_option.period_quantity}-#{renting_option.period_type.downcase}"
            renting_variant.renting_option_id = renting_option.id
            renting_variant.position = index + 2
            renting_variant.save
          end
          buying_variant = build_common_variant(master_attributes, buy_ov)
          buying_variant.sku = buying_variant.sku + "-buy"
          buying_variant.position = 1
          buying_variant.save
        end
      end

      def build_common_variant(master_attributes, option_value)
        temp_variant = @object.variants.build(master_attributes)
        temp_variant.price = @object.master.price
        temp_variant.option_values_variants.build(option_value: option_value)
        temp_variant
      end

      def has_any_renting_options_params?
        permitted_resource_params[:renting_options].present? &&
          permitted_resource_params[:renting_options].any?(&:present?)
      end
    end
  end
end

app/controllers/spree/admin/renting_options_controller.rb
module Spree
  module Admin
    class RentingOptionsController < ResourceController

      def update_values_positions
        params[:positions].each do |id, index|
          Spree::RentingOption.where(id: id).update_all(position: index)
        end

        respond_to do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js { render plain: 'Ok' }
        end
      end

      private

      def location_after_save
        edit_admin_renting_option_url(@renting_option)
      end

      def load_product
        @product = Spree::Product.find_by_param!(params[:product_id])
      end
    end
  end
end

app/controllers/spree/admin/variants_controller_decorator.rb
module Spree
  module Admin
    VariantsController.class_eval do
      update.after :attach_renting_option_values
      create.after :attach_renting_option_values

      private
      def attach_renting_option_values
        if permitted_resource_params[:spree_renting_option_id].present?
          renting_values = Spree::OptionValue.where(spree_option_values: { is_renting: true })
          buy_ov, rent_ov = renting_values.first, renting_values.second
          unless @object.option_values.where(is_renting: true, name: 'rent').any?
            @object.option_values_variants.build(option_value: rent_ov)
          end
          @object.save
        end
      end
    end
  end
end

app/views/spree/admin/products/_edit_renting_option_field.html.erb
<div data-hook="new_product_renting_option">
  <%= f.field_container :renting_option do %>
    <%= f.label :renting_option_id, Spree::RentingOption.model_name.human %>
    <%= f.field_hint :renting_option %>
    <%= f.collection_select(:renting_option_id,
      Spree::RentingOption.all, :id, :presentation,
      { :include_blank => Spree.t('match_choices.none') },
      { :class => 'select2',
        :name => 'product[spree_renting_option_id]' }) %>
    <%= f.error_message_on :renting_option %>
  <% end %>
</div>

app/views/spree/admin/products/_renting_option_fields.html.erb
<div data-hook="new_product_renting_option" class="col-xs-3">
  <%= f.field_container :renting_option do %>
    <%= f.label :renting_option, 'Renting Options' %>
    <%= f.field_hint :renting_option %>
    <%= f.collection_select(:renting_options,
      Spree::RentingOption.all, :id, :presentation,
      {},
      { :class => 'select2 fullwidth',
        multiple: true,
        size: 3,
        style: 'height: 100%'}) %>
    <%= f.error_message_on :renting_options %>
  <% end %>
</div>

app/views/spree/admin/renting_options/_form.html.erb
<div data-hook="admin_renting_option_form_fields" class="align-center row">
  <div class="col-xs-8">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required' %><br />
      <%= f.text_field :name, :class => "fullwidth" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="col-xs-2">
    <%= f.field_container :period_quantity do %>
      <%= f.label :period_quantity, class: 'required' %><br />
      <%= f.number_field :period_quantity, :class => "fullwidth" %>
      <%= f.error_message_on :period_quantity %>
    <% end %>
  </div>

  <div class="col-xs-2">
    <%= f.field_container :period_type do %>
      <%= f.label :period_type, class: 'required' %><br />
      <%= f.collection_select(:period_type,
        Spree::RentingOption.period_types.to_a, :first, :first,
        {:class => "fullwidth"},
        {prompt: 'Please select the period type'}) %>
      <%= f.error_message_on :period_type %>
    <% end %>
  </div>
</div>

app/views/spree/admin/renting_options/edit.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::RentingOption), spree.admin_renting_options_path) %>
<% admin_breadcrumb(@renting_option.name) %>

<% content_for :page_actions do %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @renting_option } %>

<%= form_for [:admin, @renting_option] do |f| %>

  <fieldset class="no-border-bottom">
    <legend><%= Spree::RentingOption.model_name.human %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/renting_options/index.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(plural_resource_name(Spree::RentingOption)) %>


<% content_for :page_actions do %>
  <% if can?(:create, Spree::RentingOption) %>
    <li id="new_ot_link">
      <%= button_link_to Spree.t(:new_renting_option), new_admin_renting_option_url, { :remote => true, :id => 'new_renting_option_link' } %>
    </li>
  <% end %>
<% end %>

<div id="new_renting_option"></div>

<% if @renting_options.any? %>
<table class="index sortable" id="listing_renting_options" data-hook="listing-renting-options" data-sortable-link="<%= update_positions_admin_renting_options_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 35%">
    <col style="width: 40%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree::RentingOption.human_attribute_name(:name) %></th>
      <th>Presentation</th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @renting_options.each do |renting_option| %>
      <tr class="spree_renting_option <%= cycle('odd', 'even')%>" id="<%= spree_dom_id renting_option %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= renting_option.name %></td>
        <td class="align-center presentation"><%= renting_option.presentation %></td>
        <td class="actions">
          <% if can?(:update, renting_option) %>
            <%= link_to_edit(renting_option, :class => 'admin_edit_renting_option', :no_text => true) %>
          <% end %>
          <% if can?(:destroy, renting_option) %>
            <%= link_to_delete(renting_option, :no_text => true) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="col-xs-9 no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::RentingOption,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

app/views/spree/admin/renting_options/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @renting_option } %>

<%= form_for [:admin, @renting_option] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:new_renting_option) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/renting_options/new.js.erb
$("#new_renting_option").html('<%= escape_javascript(render :template => "spree/admin/renting_options/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_renting_option_link").parent().hide();

app/views/spree/admin/shared/_product_renting_options_tab.html.erb
<% if can? :admin, Spree::RentingOption %>
  <%= tab :renting_options, match_path: '/renting_options' %>
<% end %>

app/views/spree/admin/variants/_renting_option_field.html.erb
<div class="col-xs-3">
  <div class="field" data-hook="renting-option">
    <%= f.label :renting_option %>
    <%= f.collection_select :renting_option_id,
                            Spree::RentingOption.all,
                            :id,
                            :presentation,
                            { include_blank: Spree.t(:select_renting_option, scope: [:admin, :renting_options]) },
                            {
                              name: 'variant[spree_renting_option_id]',
                              class: "select2 fullwidth"
                            } %>
  </div>
</div>

app/views/spree/checkout/_renting_column.html.erb
<% if item.variant.renting_option.present? %>
<td class="item-name">
  <%= item.variant.name %> <span class="renting">[Renting <%= item.variant.renting_option.presentation %>]</span>
</td>
<% end %>

app/views/spree/orders/_cart_renting_alert.html.erb
<% if variant.renting_option.present? %>
<br />
<span class="line-item-renting-option" data-hook="line_item_renting_option">
[<%= variant.renting_option.presentation %>]
</span>
<% end %>

app/views/spree/products/_cart_renting_alert_price.html.erb
 <span class="renting-option renting">
   <% if @product.renting_option && !@product.variants.pluck(:spree_renting_option_id).any? %>
    (<%= @product.renting_option.presentation %>)
   <% end %>
 </span>

app/views/spree/products/_radio_replacement.html.erb
<%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => variant.price_for(current_pricing_options), 'data-rentingperiod' => (variant.renting_option.nil?? '' : variant.renting_option.presentation) %>

app/views/spree/products/_renting_alert.html.erb
<% if variant.renting_option.present? %>
<span class="renting">[<%= variant.renting_option.presentation %>]</span>
<% end %>

app/views/spree/shared/_renting_alert.html.erb
<% if item.variant.renting_option.present? %>
<br />
<span class="line-item-renting-option" data-hook="order-details-line_item_renting_option">
[<%= item.variant.renting_option.presentation %>]
</span>
<% end %>